.\" Manpage for i281 Compiler.
.TH man 8 "28 January 2020" "0.4.8" "i281compiler man page"


.SH NAME
i281compiler \- Compiler for the i281 Microprocessor
.SH SYNOPSIS
i281compiler 
[\fB
\-h
\fR] 
[\fB
\-f
\fR] 
[\fB
\-v
\fR] 
[\fB
\-\-version
\fR]
[\fB
\-i 
\fIfilename\fR [filename...] ]
.SH DESCRIPTION
The compiler supports the compilation of i281 architecture assembly 
code to be converted to Verilog HDL and machine code (pure binary).
Outside of the basic operation of compilation, the compiler is capable
of handling multiple programs at once to reduce the number of calls
command line calls.
.SH COMMAND LINE OPTIONS
.TP
.B \-h , \-\-help
Opens the help/usage command menu.
.TP
.B \-i
Program will compile the following files after the designated argument.
.TP
.B \-v , \-\-verbose
Outpus more information to the terminal, such as: original source code, possible
process that may occur, compiled machine code, full path descriptions, etc.
.TP
.B \-\-version
Prints the version number of the exectuable and the necessary Python
version.  Program exits after this function.
.TP
.B \-f, \-\-force
Forces all prompts to default.  i.e. Overwrite prompts will overwrite by
default.
.SH AUTHOR
Original Java compiler written by Alexander Stoytchev (alexs@iastate.edu) 
and Kyung-Tae Kim.
.PP
Python compiler written by Brandt Damman (bddamman@iastate.edu)
